/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customercare.Offers;

/**
 *
 * @author Shahrear
 */
public class OfferType extends javax.swing.JFrame {
    String VoiceOrInternet,SpVoiceOrIn;
    public static String ServiceProviderName;
    /**
     * Creates new form OfferType
     */
    public OfferType(String sp) {
        initComponents();
        System.err.println("robi after identifier");
        this.ServiceProviderName=sp;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voice = new javax.swing.JButton();
        internet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1047, 660));
        setPreferredSize(new java.awt.Dimension(1047, 660));
        getContentPane().setLayout(null);

        voice.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        voice.setText("Voice Offers");
        voice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceActionPerformed(evt);
            }
        });
        getContentPane().add(voice);
        voice.setBounds(419, 252, 219, 45);

        internet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        internet.setText("Internet Offers");
        internet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetActionPerformed(evt);
            }
        });
        getContentPane().add(internet);
        internet.setBounds(419, 373, 219, 45);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Offers/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(59, 47, 110, 60);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Offer Type");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(435, 59, 203, 79);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Offers/042e750cbc58c97de7c0a07512475e5d.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -5, 1050, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceActionPerformed
        VoiceOrInternet ="voice";
        SpVoiceOrIn=ServiceProviderName+VoiceOrInternet;
        BuyOffer sfn=new BuyOffer(SpVoiceOrIn);
        sfn.setVisible(true);
        dispose();
    }//GEN-LAST:event_voiceActionPerformed

    private void internetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetActionPerformed
        VoiceOrInternet ="internet";
        SpVoiceOrIn=ServiceProviderName+VoiceOrInternet;
        BuyOffer gpfl=new BuyOffer(SpVoiceOrIn);
        System.err.println("robi after internet");
        gpfl.setVisible(true);
        dispose();
    }//GEN-LAST:event_internetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        offersForm of=new offersForm();
        of.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfferType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfferType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfferType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfferType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfferType(ServiceProviderName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton internet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton voice;
    // End of variables declaration//GEN-END:variables
}
