/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customercare.AirtimeRecharge;

import com.mysql.jdbc.Connection;
import static customercare.database.ICrudImpl.ip;
import customercare.ui.HomePage;
import customercare.ui.Login;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahrear
 */
public class AirtimeForm extends javax.swing.JFrame {
    private Connection connection;
    public String un,mobile;
    public int balanceDB,airtimeDB;
    /**
     * Creates new form AirtimeForm
     */
    public AirtimeForm() {
        initComponents();
       un = Login.UName;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        airtimeAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pn = new javax.swing.JTextField();
        serviceProvider = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        walletMoney = new javax.swing.JTextField();
        airtimeBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1047, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        Back.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/AirtimeRecharge/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Airtime Recharge");

        Refresh.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/AirtimeRecharge/refresh.png"))); // NOI18N
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Refresh)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 140));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Airtime Amount :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, 39));

        airtimeAmount.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        airtimeAmount.setText("0");
        getContentPane().add(airtimeAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 118, 39));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Number :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 94, 39));

        Pn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(Pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 160, 39));

        serviceProvider.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        serviceProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GrameenPhone", "Airtel", "Robi", "Banglalink", "Teletalk" }));
        getContentPane().add(serviceProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, 39));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Service Provider :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 111, 39));

        OK.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, 36));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Wallet Money :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 94, 39));

        walletMoney.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(walletMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 118, 39));

        airtimeBalance.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        airtimeBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(airtimeBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 67, 42));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Airtime");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 67, 28));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Taka");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/AirtimeRecharge/wallpaper-background-32.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 1040, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        HomePage hp=new HomePage();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
           Connection con =openConnection();
        try {
            Statement state = con.createStatement();
            ResultSet resultset = state.executeQuery("select * from user3 where username = '"+Login.UName+"'");
            //System.out.println(un);
            if(resultset.next())
            {
               
                walletMoney.setText(resultset.getString("money"));
                balanceDB=Integer.parseInt(resultset.getString("money"));
                airtimeBalance.setText(resultset.getString("airtime"));
                airtimeDB=Integer.parseInt(resultset.getString("airtime"));
                //mobile=resultset.getString("mobile");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AirtimeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        String aAmount=this.airtimeAmount.getText();
        int a1Amount=Integer.parseInt(aAmount);
        int flag=0;
        String pn=Pn.getText();
        String sp=(String) this.serviceProvider.getSelectedItem();
        if(a1Amount>balanceDB)
        {
            JOptionPane.showMessageDialog(null,"You are out of money,refill your wallet !!","Sorry! You can't buy airtime",JOptionPane.WARNING_MESSAGE);
        }
        if(pn.length()!=11)
        {
            JOptionPane.showMessageDialog(null,"You must enter a valid number !!","Unvallid number",JOptionPane.WARNING_MESSAGE);
        }
        else if((pn.charAt(2)=='6' && sp.equals("Airtel") || pn.charAt(2)=='7' && sp.equals("GrameenPhone") ||pn.charAt(2)=='5' && sp.equals("Teletalk") ||pn.charAt(2)=='8' && sp.equals("Robi") ||pn.charAt(2)=='9' && sp.equals("Banglalink"))&& balanceDB>a1Amount )
        {
            balanceDB-=a1Amount;
            airtimeDB+=a1Amount;
            String BalanceDB=Integer.toString(balanceDB);
            String AirtimeDB=Integer.toString(airtimeDB);
            Connection con =openConnection();
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET airtime = ? where username = ?");
                preparedStatement.setString(1, AirtimeDB);
                preparedStatement.setString(2, Login.UName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AirtimeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET money= ? where username = ?");
                preparedStatement.setString(1, BalanceDB);
                preparedStatement.setString(2, Login.UName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AirtimeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
          JOptionPane.showMessageDialog(null,"Your account refilled with "+aAmount+" Taka successfully :) ","Confirmation message",JOptionPane.INFORMATION_MESSAGE); 
        }
        else
        {
            JOptionPane.showMessageDialog(null,"You are mobile number mismatch with service provider!!","Sorry! You can't buy airtime",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_OKActionPerformed
        public Connection openConnection()
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                this.connection=(Connection) DriverManager.getConnection("jdbc:mysql://"+ip+"/java_db?useSSL=false","root","123");
                System.out.println("Connection established successfully with the database server,airtime Form");
            } catch (Exception e) {
                System.out.println("Error"+e.getMessage());
            }
           return this.connection;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirtimeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirtimeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirtimeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirtimeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirtimeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton OK;
    private javax.swing.JTextField Pn;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextField airtimeAmount;
    private javax.swing.JTextField airtimeBalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> serviceProvider;
    private javax.swing.JTextField walletMoney;
    // End of variables declaration//GEN-END:variables
}
