/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customercare.wallet;

import customercare.ui.HomePage;

/**
 *
 * @author Shahrear
 */
public class walletRefillForm extends javax.swing.JFrame {

    /**
     * Creates new form walletRefillForm
     */
    public walletRefillForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StandardCharterd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CityBank = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IslamiBank = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BankAsia = new javax.swing.JButton();
        dbbl = new javax.swing.JButton();
        BracBank = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1047, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StandardCharterd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/standardCharterd.jpg"))); // NOI18N
        StandardCharterd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardCharterdActionPerformed(evt);
            }
        });
        getContentPane().add(StandardCharterd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 109, 68));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Islami Bank");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 109, 25));

        CityBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/cityBank.jpg"))); // NOI18N
        CityBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityBankActionPerformed(evt);
            }
        });
        getContentPane().add(CityBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 109, 70));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("City Bank");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 109, -1));

        IslamiBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/ib.jpg"))); // NOI18N
        IslamiBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IslamiBankActionPerformed(evt);
            }
        });
        getContentPane().add(IslamiBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 109, 70));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Standard Chartered");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 109, 23));

        BankAsia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/BankAsia.jpg"))); // NOI18N
        BankAsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankAsiaActionPerformed(evt);
            }
        });
        getContentPane().add(BankAsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 108, 71));

        dbbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/dbbl.jpg"))); // NOI18N
        dbbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbblActionPerformed(evt);
            }
        });
        getContentPane().add(dbbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 109, 71));

        BracBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/bb.jpg"))); // NOI18N
        BracBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BracBankActionPerformed(evt);
            }
        });
        getContentPane().add(BracBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 109, 71));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bank Asia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 109, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DBBL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 109, 25));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Brac Bank");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 109, 25));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Select Your");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 70));

        Back.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/Banks.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 90, 70));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Bank");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/wallet/blue-watercolor-sky-and-clouds-background.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IslamiBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IslamiBankActionPerformed
        IslamiBankForm ibf=new IslamiBankForm();
        ibf.setVisible(true);
    }//GEN-LAST:event_IslamiBankActionPerformed

    private void CityBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityBankActionPerformed
        CityBankForm cbf=new CityBankForm();
        cbf.setVisible(true);
    }//GEN-LAST:event_CityBankActionPerformed

    private void StandardCharterdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardCharterdActionPerformed
        StandardCharteredForm sc=new StandardCharteredForm();
        sc.setVisible(true);
    }//GEN-LAST:event_StandardCharterdActionPerformed

    private void BankAsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankAsiaActionPerformed
        // TODO add your handling code here:
        BankAsiaForm baf=new BankAsiaForm();
        baf.setVisible(true);
        
    }//GEN-LAST:event_BankAsiaActionPerformed

    private void dbblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbblActionPerformed
        // TODO add your handling code here:
        DBBLForm df=new DBBLForm();
        df.setVisible(true);
    }//GEN-LAST:event_dbblActionPerformed

    private void BracBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BracBankActionPerformed
        // TODO add your handling code here:
        BracBankForm bbf=new BracBankForm();
        bbf.setVisible(true);
    }//GEN-LAST:event_BracBankActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        HomePage hp=new HomePage();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BankAsia;
    private javax.swing.JButton BracBank;
    private javax.swing.JButton CityBank;
    private javax.swing.JButton IslamiBank;
    private javax.swing.JButton StandardCharterd;
    private javax.swing.JButton dbbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
