package customercare.Admin;


/**
 *
 * @author Shahrear
 */
public class AdminForm extends javax.swing.JFrame {
    public static String serviceProviderName;
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gp = new javax.swing.JButton();
        airtel = new javax.swing.JButton();
        robi = new javax.swing.JButton();
        banglalink = new javax.swing.JButton();
        teletalk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1047, 660));
        getContentPane().setLayout(null);

        gp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gp.setText("Grameen Phone");
        gp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpActionPerformed(evt);
            }
        });
        getContentPane().add(gp);
        gp.setBounds(450, 178, 138, 43);

        airtel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        airtel.setText("Airtel");
        airtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airtelActionPerformed(evt);
            }
        });
        getContentPane().add(airtel);
        airtel.setBounds(450, 252, 138, 43);

        robi.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        robi.setText("Robi");
        robi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robiActionPerformed(evt);
            }
        });
        getContentPane().add(robi);
        robi.setBounds(450, 330, 138, 43);

        banglalink.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        banglalink.setText("Banglalink");
        banglalink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banglalinkActionPerformed(evt);
            }
        });
        getContentPane().add(banglalink);
        banglalink.setBounds(450, 412, 138, 43);

        teletalk.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        teletalk.setText("Teletalk");
        teletalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teletalkActionPerformed(evt);
            }
        });
        getContentPane().add(teletalk);
        teletalk.setBounds(450, 493, 138, 43);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Admin/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(68, 71, 110, 59);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Admin/1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 1040, 660);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Service Providers");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 40, 210, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teletalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teletalkActionPerformed
        serviceProviderName="teletalk";
        gpSelectionForm gpsf=new gpSelectionForm(serviceProviderName);
        gpsf.setVisible(true);
        dispose();
    }//GEN-LAST:event_teletalkActionPerformed

    private void banglalinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banglalinkActionPerformed
        serviceProviderName="banglalink";
        gpSelectionForm gpsf=new gpSelectionForm(serviceProviderName);
        gpsf.setVisible(true);
        dispose();
    }//GEN-LAST:event_banglalinkActionPerformed

    private void robiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robiActionPerformed
        serviceProviderName="robi";
        gpSelectionForm gpsf=new gpSelectionForm(serviceProviderName);
        gpsf.setVisible(true);
        dispose();
    }//GEN-LAST:event_robiActionPerformed

    private void airtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airtelActionPerformed
        serviceProviderName="airtel";
        gpSelectionForm gpsf=new gpSelectionForm(serviceProviderName);
        gpsf.setVisible(true);
        dispose();
    }//GEN-LAST:event_airtelActionPerformed

    private void gpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpActionPerformed
        serviceProviderName="gp";
        gpSelectionForm gpsf=new gpSelectionForm(serviceProviderName);
        gpsf.setVisible(true);
        dispose();
    }//GEN-LAST:event_gpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SuperAdmin sa=new SuperAdmin();
        sa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airtel;
    private javax.swing.JButton banglalink;
    private javax.swing.JButton gp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton robi;
    private javax.swing.JButton teletalk;
    // End of variables declaration//GEN-END:variables
}
