/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customercare.Admin;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.ServerSocket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.Query;

/**
 *
 * @author Shahrear
 */
public class ApproveBalaceRequestChat extends javax.swing.JFrame {

    static ServerSocket ss;
    static Socket s;
    static DataOutputStream dout;
    static DataInputStream din;
    private Connection connection;
    static String userName;

    /**
     * Creates new form ServerChat
     */
    public ApproveBalaceRequestChat() throws IOException {
        initComponents();
        /*System.out.println("serverchat");*/
        ss = new ServerSocket(1201);
        s = ss.accept();
        din = new DataInputStream(s.getInputStream());
        dout = new DataOutputStream(s.getOutputStream());
        new recev().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        approved = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IslamiBank = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CityBank = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        StandardChartered = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BankAsia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dbbl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BracBank = new javax.swing.JTextField();
        discard = new javax.swing.JButton();
        IdIslamiBank = new javax.swing.JTextField();
        IdCityBank = new javax.swing.JTextField();
        IdStandardChartred = new javax.swing.JTextField();
        IdBankAsia = new javax.swing.JTextField();
        IdDbbl = new javax.swing.JTextField();
        IdBracBank = new javax.swing.JTextField();
        PinIslamiBank = new javax.swing.JTextField();
        PinCityBank = new javax.swing.JTextField();
        PinStandardChartred = new javax.swing.JTextField();
        PinBankAsia = new javax.swing.JTextField();
        PinDbbl = new javax.swing.JTextField();
        PinBracBank = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1047, 660));
        setPreferredSize(new java.awt.Dimension(1047, 660));
        getContentPane().setLayout(null);

        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(810, 180, 29, 40);

        approved.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        approved.setText("Update");
        approved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvedActionPerformed(evt);
            }
        });
        getContentPane().add(approved);
        approved.setBounds(460, 510, 91, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Islami Bank :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 170, 95, 30);

        IslamiBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IslamiBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IslamiBank.setText("0");
        getContentPane().add(IslamiBank);
        IslamiBank.setBounds(330, 170, 103, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("City Bank :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 220, 95, 30);

        CityBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        CityBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CityBank.setText("0");
        getContentPane().add(CityBank);
        CityBank.setBounds(330, 220, 103, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Standard Chartered :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(135, 270, 120, 30);

        StandardChartered.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        StandardChartered.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StandardChartered.setText("0");
        getContentPane().add(StandardChartered);
        StandardChartered.setBounds(330, 270, 103, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Bank Asia :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 330, 95, 30);

        BankAsia.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BankAsia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BankAsia.setText("0");
        getContentPane().add(BankAsia);
        BankAsia.setBounds(330, 330, 103, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DBBL :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 380, 95, 30);

        dbbl.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        dbbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dbbl.setText("0");
        getContentPane().add(dbbl);
        dbbl.setBounds(330, 380, 103, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Brac Bank :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 430, 95, 30);

        BracBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BracBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BracBank.setText("0");
        getContentPane().add(BracBank);
        BracBank.setBounds(330, 430, 103, 30);

        discard.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        discard.setText("Discard");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });
        getContentPane().add(discard);
        discard.setBounds(670, 510, 85, 50);

        IdIslamiBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IdIslamiBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdIslamiBank.setText("0");
        getContentPane().add(IdIslamiBank);
        IdIslamiBank.setBounds(460, 170, 148, 30);

        IdCityBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IdCityBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdCityBank.setText("0");
        getContentPane().add(IdCityBank);
        IdCityBank.setBounds(460, 220, 148, 30);

        IdStandardChartred.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IdStandardChartred.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdStandardChartred.setText("0");
        getContentPane().add(IdStandardChartred);
        IdStandardChartred.setBounds(460, 270, 148, 30);

        IdBankAsia.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IdBankAsia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdBankAsia.setText("0");
        getContentPane().add(IdBankAsia);
        IdBankAsia.setBounds(460, 330, 148, 30);

        IdDbbl.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IdDbbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdDbbl.setText("0");
        getContentPane().add(IdDbbl);
        IdDbbl.setBounds(460, 380, 148, 30);

        IdBracBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        IdBracBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdBracBank.setText("0");
        getContentPane().add(IdBracBank);
        IdBracBank.setBounds(460, 430, 148, 30);

        PinIslamiBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PinIslamiBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinIslamiBank.setText("0");
        getContentPane().add(PinIslamiBank);
        PinIslamiBank.setBounds(650, 170, 109, 30);

        PinCityBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PinCityBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinCityBank.setText("0");
        getContentPane().add(PinCityBank);
        PinCityBank.setBounds(650, 220, 109, 30);

        PinStandardChartred.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PinStandardChartred.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinStandardChartred.setText("0");
        getContentPane().add(PinStandardChartred);
        PinStandardChartred.setBounds(650, 270, 109, 30);

        PinBankAsia.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PinBankAsia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinBankAsia.setText("0");
        getContentPane().add(PinBankAsia);
        PinBankAsia.setBounds(650, 330, 109, 30);

        PinDbbl.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PinDbbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinDbbl.setText("0");
        getContentPane().add(PinDbbl);
        PinDbbl.setBounds(650, 380, 109, 30);

        PinBracBank.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PinBracBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinBracBank.setText("0");
        getContentPane().add(PinBracBank);
        PinBracBank.setBounds(650, 430, 109, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Money");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 130, 128, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Card No");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 130, 110, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PIN");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(650, 130, 29, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Server Site");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 40, 370, 60);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("(Please enter at least 4 digit  for your security)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(690, 130, 224, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Admin/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 30, 110, 60);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Admin/Arkaplan2XCUAFKDINS17668.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -5, 1050, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvedActionPerformed
        try {
            String msgout = "";
            System.out.println("dfsdsdfsd");
            msgout = "Your request Approved".trim();
            dout.writeUTF(msgout);

            //msg_area.setText(msg_area.getText().trim() + "\nDoctor: " + msgout);
            //msg_area.setFocusable(false);
            //msg_text.setText(null);
            Connection con=openConnection();
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET islamibank = ? where username = ?");
                preparedStatement.setString(1, IslamiBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET citybank = ? where username = ?");
                preparedStatement.setString(1, CityBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET standardchartered = ? where username = ?");
                preparedStatement.setString(1, StandardChartered.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET bankasia = ? where username = ?");
                preparedStatement.setString(1, BankAsia.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET dbbl = ? where username = ?");
                preparedStatement.setString(1, dbbl.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET bracbank = ? where username = ?");
                preparedStatement.setString(1, BracBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET idislmibank = ? where username = ?");
                preparedStatement.setString(1, IdIslamiBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET pinislamibank = ? where username = ?");
                preparedStatement.setString(1, PinIslamiBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET idcitybank = ? where username = ?");
                preparedStatement.setString(1, IdCityBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET pincitybank = ? where username = ?");
                preparedStatement.setString(1, PinCityBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET idstandard = ? where username = ?");
                preparedStatement.setString(1, IdStandardChartred.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET pinstandard = ? where username = ?");
                preparedStatement.setString(1, PinStandardChartred.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET idbankasia = ? where username = ?");
                preparedStatement.setString(1, IdBankAsia.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET pinbankasia = ? where username = ?");
                preparedStatement.setString(1, PinBankAsia.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET iddbbl = ? where username = ?");
                preparedStatement.setString(1, IdDbbl.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET pindbbl = ? where username = ?");
                preparedStatement.setString(1, PinDbbl.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET idbracbank = ? where username = ?");
                preparedStatement.setString(1, IdBracBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement preparedStatement=con.prepareStatement("UPDATE user3 SET pinbracbank = ? where username = ?");
                preparedStatement.setString(1, PinBracBank.getText());
                preparedStatement.setString(2, userName);
                preparedStatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_approvedActionPerformed

    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        try {
            String msgout = "";
            msgout = "Your request not Approved".trim();
            dout.writeUTF(msgout);

            //msg_area.setText(msg_area.getText().trim() + "\nDoctor: " + msgout);
            //msg_area.setFocusable(false);
            //msg_text.setText(null);
            

        } catch (Exception e) {

        }
    }//GEN-LAST:event_discardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SuperAdmin sp=new SuperAdmin();
        sp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public Connection openConnection(){
        Connection conn = null;
        try {
            String url = "jdbc:mysql://localhost/java_db?useSSL=false";
            
            conn = DriverManager.getConnection(url, "root","123");
        } catch (SQLException e) {
           Logger.getLogger(Query.class.getName()).log(Level.SEVERE, null, e);
        }
        return conn;
    }
    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    class recev extends Thread{

        public recev() {
            

        }

        public void run() {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ApproveBalaceRequestChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(() -> {
            new ServerChat().setVisible(true);
        });*/
            
            try {
                String msing = " ";

                
                while (!msing.equals("ShutUp")) {
                    msing = din.readUTF();
                    System.err.println(msing);
                  
                    String parts[]=msing.split(" ");
                    IslamiBank.setText(parts[0]);
                    CityBank.setText(parts[1]);
                    StandardChartered.setText(parts[2]);
                    BankAsia.setText(parts[3]);
                    dbbl.setText(parts[4]);
                    BracBank.setText(parts[5]);
                    IdIslamiBank.setText(parts[6]);
                    IdCityBank.setText(parts[7]);
                    IdStandardChartred.setText(parts[8]);
                    IdBankAsia.setText(parts[9]);
                    IdDbbl.setText(parts[10]);
                    IdBracBank.setText(parts[11]);
                    PinIslamiBank.setText(parts[12]);
                    PinCityBank.setText(parts[13]);
                    PinStandardChartred.setText(parts[14]);
                    PinBankAsia.setText(parts[15]);
                    PinDbbl.setText(parts[16]);
                    PinBracBank.setText(parts[17]);
                    userName=parts[18];
                    //msg_area.setText(msg_area.getText().trim() + "\nPatient: " + msing);
                    parts=null;
                }
            } catch (IOException e) {

            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BankAsia;
    private javax.swing.JTextField BracBank;
    private javax.swing.JTextField CityBank;
    private javax.swing.JTextField IdBankAsia;
    private javax.swing.JTextField IdBracBank;
    private javax.swing.JTextField IdCityBank;
    private javax.swing.JTextField IdDbbl;
    private javax.swing.JTextField IdIslamiBank;
    private javax.swing.JTextField IdStandardChartred;
    private javax.swing.JTextField IslamiBank;
    private javax.swing.JTextField PinBankAsia;
    private javax.swing.JTextField PinBracBank;
    private javax.swing.JTextField PinCityBank;
    private javax.swing.JTextField PinDbbl;
    private javax.swing.JTextField PinIslamiBank;
    private javax.swing.JTextField PinStandardChartred;
    private javax.swing.JTextField StandardChartered;
    private static javax.swing.JButton approved;
    private javax.swing.JTextField dbbl;
    private javax.swing.JButton discard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea msg_area;
    // End of variables declaration//GEN-END:variables
}
