/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customercare.Admin;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shahrear
 */
public class SuperAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Super
     */
    public SuperAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDataOffer = new javax.swing.JButton();
        replyClient = new javax.swing.JButton();
        ApproveBalaceRequest = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1047, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateDataOffer.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        UpdateDataOffer.setText("Update Data Pack & Offers");
        UpdateDataOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDataOfferActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateDataOffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 191, 226, 50));

        replyClient.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        replyClient.setText("Reply Client");
        replyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replyClientActionPerformed(evt);
            }
        });
        getContentPane().add(replyClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 317, 226, 46));

        ApproveBalaceRequest.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ApproveBalaceRequest.setText("Approve Bank Balace Request");
        ApproveBalaceRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveBalaceRequestActionPerformed(evt);
            }
        });
        getContentPane().add(ApproveBalaceRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 457, -1, 46));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Admin/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 51, 110, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Server");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 24, 226, 87));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customercare/Admin/white-blue-ppt-background-1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateDataOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDataOfferActionPerformed
        AdminForm af=new AdminForm();
        af.setVisible(true);
        dispose();
    }//GEN-LAST:event_UpdateDataOfferActionPerformed

    private void replyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replyClientActionPerformed
        AdminChat ch = null;
        try {
            ch = new AdminChat();
        } catch (IOException ex) {
            Logger.getLogger(AdminChat.class.getName()).log(Level.SEVERE, null, ex);
        }
        ch.setVisible(true);
    }//GEN-LAST:event_replyClientActionPerformed

    private void ApproveBalaceRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveBalaceRequestActionPerformed
        ApproveBalaceRequestChat ch = null;
        try {
            ch = new ApproveBalaceRequestChat();
        } catch (IOException ex) {
            Logger.getLogger(SuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        ch.setVisible(true);
    }//GEN-LAST:event_ApproveBalaceRequestActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveBalaceRequest;
    private javax.swing.JButton UpdateDataOffer;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton replyClient;
    // End of variables declaration//GEN-END:variables
}
